### ISSUE TITLE
Parentheses in aritmetic expressions are not handled well

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-prolog-runner#28]
In https://mumuki.io/exercises/1973-programacion-logica-inversibilidad-algunas-cuentas

This input will fail:
```
cuantaNaftaConsume(Km,Nafta):-
  Nafta is 40 * (Km / 600).
```
Using that same code in swi-prolog 7.2.3 locally will work though. Maybe the swipl version the runner uses is outdated and has problems parsing?

**Comment by julian-berbel** [comment]
On second thought though, if the docker image is up to date, the swipl version should be 7.6.4, which on a local test worked just fine as well :thinking:

**Comment by flbulgarelli** [comment]
Solved. It was an issue with the content, arithmetic operations and floating point numbers. See the diff here: 

https://github.com/pdep-utn/mumuki-guia-logico-inversibilidad/commit/6abfbc9f03820b8b4290ade0309ce67a2d7c08a9#diff-2e55bb4be7db0436efed7fdc8c5baac0
