### ISSUE TITLE
hasRedundantReduction smell is sometimes misdetected

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-prolog-runner#32]
take https://mumuki.io/exercises/2009-programacion-logica-practica-inversibilidad-puntajeequilibrioescoba for example,

The code:
```
puntajeEquilibrioEscoba(Competidor, Puntaje):-
  metrosEscoba(Competidor, Metros),
  Puntaje is round(Metros / 3).
```

Will say `is` is being used but no calculations are being made.

**Comment by flbulgarelli** [comment]
We should check this is a runner issue and not a mulang issue.

**Comment by julian-berbel** [comment]
yup, just checked, and the problem is that mulang does not know `round` is a function
