### ISSUE TITLE
Los comentarios impactan al runner

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-prolog-runner#35]
Tanto si se usa % como /*  */ para agregar comentarios en la solución pasan cosas raras, sobre todo con las inspecciones.

Puntualmente me pasó en el ejercicio 10. viajes de la guía: Práctica Listas y Findall.

![imagen](https://user-images.githubusercontent.com/715971/52969012-b4e7b480-338d-11e9-969a-2e3f147b8150.png)

![imagen](https://user-images.githubusercontent.com/715971/52969051-c7fa8480-338d-11e9-94d2-3eb54535d14a.png)

Si el comentario lo pongo arriba de tiempoTotalVuelo en vez de en el medio, muestra esto:
![imagen](https://user-images.githubusercontent.com/715971/52969119-02642180-338e-11e9-818d-91d5ecc4efa1.png)

**Comment by flbulgarelli** [comment]
Probablemente sea un problema del parser de prolog que está en Mulang.
